import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Stack } from "@mui/material";
import { useColorAssets } from "@/hooks/view/useColorAssets";
import "../../styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const ColorAssets = useColorAssets();

  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Stack
            style={{
              margin: 0,
              padding: 0,
              backgroundColor: ColorAssets.mainGreen,
              width: "100%",
              height: "100%",
            }}
          >
            {children}
          </Stack>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
